# Generated by Django 4.2.5 on 2023-11-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
